"""Expand the theory knowledge base from 296 to 400 theories.

Adds new theories across under-represented domains: Robotics, Causal Inference,
Astrophysics, Chemistry, NLP/Linguistics, Bioinformatics, Cryptography,
Complex Systems, Sociology, Behavioral Economics, Decision Theory, plus
expansion of RL, EGT, Information Theory, Cognitive Science, Operations Research.
"""
import json
from pathlib import Path

NEW_THEORIES = {
    # ── Robotics (8) ──
    "kinematic_chain": {
        "id": "kinematic_chain", "name": "Forward/Inverse Kinematics", "domain": "Robotics",
        "equation": "x = f(θ),  θ = f⁻¹(x)",
        "update_form": "geometric_composition", "optimization": "minimize_pose_error",
        "fixed_points": "configuration_singularity",
        "operators": ["matrix_product", "rotation", "translation", "jacobian"],
        "patterns": ["compositional_structure", "geometric_transformation", "dual_variables", "fixed_point_stability"],
        "variables": {"state": "joint_angles", "output": "end_effector_pose", "constraint": "link_lengths"},
        "conservation": ["link_length"], "structure": "manifold_chain",
    },
    "slam": {
        "id": "slam", "name": "SLAM (Simultaneous Localization and Mapping)", "domain": "Robotics",
        "equation": "p(x_t, m | z_{1:t}, u_{1:t}) ∝ p(z_t | x_t, m) · p(x_t | x_{t-1}, u_t)",
        "update_form": "recursive_bayesian", "optimization": "maximize_posterior",
        "fixed_points": "consistent_map",
        "operators": ["bayes_rule", "marginalize", "predict", "update"],
        "patterns": ["bayesian_inference", "prediction_error_correction", "recursive_estimation", "joint_estimation"],
        "variables": {"state": "robot_pose", "map": "landmark_positions", "observation": "sensor_readings"},
        "conservation": ["measurement_consistency"], "structure": "probabilistic_graphical_model",
    },
    "model_predictive_control": {
        "id": "model_predictive_control", "name": "Model Predictive Control (MPC)", "domain": "Robotics",
        "equation": "u* = argmin_u Σ_{k=0}^{N} L(x_k, u_k) + V_f(x_N)",
        "update_form": "receding_horizon", "optimization": "minimize_cost_horizon",
        "fixed_points": "steady_state_control",
        "operators": ["forward_simulate", "minimize", "constrain", "receding_horizon_shift"],
        "patterns": ["recursive_decomposition", "constrained_optimization", "rolling_window", "predict_then_act"],
        "variables": {"state": "system_state", "control": "input_sequence", "horizon": "prediction_window"},
        "conservation": ["constraint_satisfaction"], "structure": "constrained_optimization",
    },
    "imitation_learning": {
        "id": "imitation_learning", "name": "Imitation Learning / Behavior Cloning", "domain": "Robotics",
        "equation": "π* = argmin_π E_{(s,a)~D}[L(π(s), a)]",
        "update_form": "supervised_loss_minimization", "optimization": "match_expert_distribution",
        "fixed_points": "expert_policy",
        "operators": ["sample", "minimize_loss", "regress", "distill"],
        "patterns": ["distribution_matching", "gradient_descent", "supervised_learning"],
        "variables": {"state": "observation", "action": "expert_demonstration", "policy": "learned_mapping"},
        "conservation": ["expert_distribution"], "structure": "supervised_regression",
    },
    "force_torque_control": {
        "id": "force_torque_control", "name": "Force/Torque Control", "domain": "Robotics",
        "equation": "τ = M(q)q̈ + C(q,q̇)q̇ + G(q) + J^T F",
        "update_form": "dynamics_inversion", "optimization": "track_force_trajectory",
        "fixed_points": "compliant_contact",
        "operators": ["matrix_inverse", "jacobian_transpose", "feedback"],
        "patterns": ["feedback_control", "dual_variables", "constraint_dynamics", "energy_based"],
        "variables": {"state": "joint_torque", "force": "contact_wrench", "dynamics": "manipulator_equation"},
        "conservation": ["energy", "momentum"], "structure": "constrained_dynamics",
    },
    "swarm_robotics": {
        "id": "swarm_robotics", "name": "Swarm Robotics / Boids", "domain": "Robotics",
        "equation": "v_i = α·separation + β·alignment + γ·cohesion",
        "update_form": "local_interaction_rules", "optimization": "emergent_collective_behavior",
        "fixed_points": "flocking_consensus",
        "operators": ["local_sum", "average", "subtract", "weight"],
        "patterns": ["emergence", "local_interaction", "self_organization", "consensus"],
        "variables": {"state": "agent_velocity", "neighborhood": "local_agents", "rule": "interaction_weights"},
        "conservation": ["collective_momentum"], "structure": "agent_based_model",
    },
    "reinforcement_robot_learning": {
        "id": "reinforcement_robot_learning", "name": "Robot RL (Sim-to-Real)", "domain": "Robotics",
        "equation": "π* = argmax_π E_{sim,real}[Σ γ^t r_t]",
        "update_form": "domain_randomized_gradient", "optimization": "robust_policy",
        "fixed_points": "domain_invariant_policy",
        "operators": ["randomize_params", "policy_gradient", "transfer"],
        "patterns": ["domain_adaptation", "exploration_exploitation", "robust_optimization"],
        "variables": {"state": "robot_state", "policy": "control_network", "domain": "simulation_params"},
        "conservation": ["task_reward"], "structure": "policy_optimization",
    },
    "tactile_perception": {
        "id": "tactile_perception", "name": "Tactile Perception / Haptic Inference", "domain": "Robotics",
        "equation": "p(object | contact_signal) ∝ p(contact_signal | object) · p(object)",
        "update_form": "active_sensing", "optimization": "minimize_perceptual_uncertainty",
        "fixed_points": "identified_object",
        "operators": ["sense", "infer", "act_to_disambiguate"],
        "patterns": ["bayesian_inference", "active_inference", "information_gain"],
        "variables": {"state": "object_identity", "observation": "tactile_signal", "action": "exploratory_touch"},
        "conservation": ["sensor_calibration"], "structure": "active_perception_loop",
    },

    # ── Causal Inference (6) ──
    "do_calculus": {
        "id": "do_calculus", "name": "Pearl's do-Calculus", "domain": "Causal Inference",
        "equation": "P(Y | do(X)) ≠ P(Y | X)",
        "update_form": "intervention_rule", "optimization": "identify_causal_effect",
        "fixed_points": "identifiable_estimand",
        "operators": ["intervene", "marginalize", "condition", "graph_surgery"],
        "patterns": ["intervention", "counterfactual_reasoning", "graph_structure", "conditional_independence"],
        "variables": {"state": "outcome", "treatment": "intervention", "confounder": "backdoor_variable"},
        "conservation": ["causal_structure"], "structure": "directed_acyclic_graph",
    },
    "instrumental_variables": {
        "id": "instrumental_variables", "name": "Instrumental Variables", "domain": "Causal Inference",
        "equation": "β = Cov(Y,Z) / Cov(X,Z)",
        "update_form": "two_stage_regression", "optimization": "consistent_causal_estimate",
        "fixed_points": "identifiable_effect",
        "operators": ["project", "regress_two_stage", "exclude"],
        "patterns": ["exclusion_restriction", "exogenous_variation", "identification"],
        "variables": {"state": "outcome", "treatment": "endogenous_var", "instrument": "exogenous_var"},
        "conservation": ["exclusion_restriction"], "structure": "moment_condition",
    },
    "potential_outcomes": {
        "id": "potential_outcomes", "name": "Potential Outcomes / Rubin Causal Model", "domain": "Causal Inference",
        "equation": "ATE = E[Y(1) - Y(0)]",
        "update_form": "counterfactual_difference", "optimization": "estimate_treatment_effect",
        "fixed_points": "average_treatment_effect",
        "operators": ["expectation", "subtract_counterfactual", "match"],
        "patterns": ["counterfactual_reasoning", "ignorability", "treatment_effect"],
        "variables": {"state": "potential_outcome", "treatment": "binary_assignment", "covariate": "pre_treatment_var"},
        "conservation": ["sutva"], "structure": "counterfactual_framework",
    },
    "propensity_score": {
        "id": "propensity_score", "name": "Propensity Score Matching", "domain": "Causal Inference",
        "equation": "e(X) = P(T=1 | X)",
        "update_form": "reweight_match", "optimization": "balance_covariates",
        "fixed_points": "balanced_treatment_groups",
        "operators": ["estimate_propensity", "match", "weight", "stratify"],
        "patterns": ["balancing", "dimension_reduction", "confounding_adjustment"],
        "variables": {"state": "covariate", "treatment": "assignment", "propensity": "treatment_probability"},
        "conservation": ["balance_property"], "structure": "matching_framework",
    },
    "regression_discontinuity": {
        "id": "regression_discontinuity", "name": "Regression Discontinuity Design", "domain": "Causal Inference",
        "equation": "τ = lim_{x→c⁺} E[Y|X=x] - lim_{x→c⁻} E[Y|X=x]",
        "update_form": "discontinuity_estimation", "optimization": "local_average_treatment_effect",
        "fixed_points": "threshold_jump",
        "operators": ["limit", "subtract", "local_regression"],
        "patterns": ["threshold_effect", "local_randomization", "discontinuity"],
        "variables": {"state": "outcome", "running_var": "assignment_variable", "cutoff": "threshold"},
        "conservation": ["smoothness_below_above"], "structure": "local_polynomial_regression",
    },
    "synthetic_control": {
        "id": "synthetic_control", "name": "Synthetic Control Method", "domain": "Causal Inference",
        "equation": "Y₁ᵗʳᵉᵃᵗ - Σ wⱼ Yⱼᶜᵒⁿᵗʳᵒˡ",
        "update_form": "weighted_donor_pool", "optimization": "minimize_pre_treatment_mse",
        "fixed_points": "constructed_counterfactual",
        "operators": ["weight_average", "minimize", "match_trajectory"],
        "patterns": ["counterfactual_construction", "convex_combination", "pre_treatment_matching"],
        "variables": {"state": "outcome_trajectory", "weight": "donor_weights", "treatment": "policy_change"},
        "conservation": ["simplex_constraint"], "structure": "constrained_least_squares",
    },

    # ── Astrophysics / Cosmology (8) ──
    "friedmann_equations": {
        "id": "friedmann_equations", "name": "Friedmann Equations", "domain": "Astrophysics",
        "equation": "H² = (8πG/3)ρ - kc²/a² + Λc²/3",
        "update_form": "general_relativity_evolution", "optimization": "scale_factor_dynamics",
        "fixed_points": "cosmological_attractor",
        "operators": ["differential", "tensor_contract", "integrate"],
        "patterns": ["energy_conservation", "scale_invariance", "geometric_evolution"],
        "variables": {"state": "scale_factor", "energy": "density", "geometry": "curvature"},
        "conservation": ["stress_energy_tensor"], "structure": "ode_on_metric",
    },
    "stellar_structure": {
        "id": "stellar_structure", "name": "Stellar Structure Equations", "domain": "Astrophysics",
        "equation": "dP/dr = -Gm(r)ρ/r²",
        "update_form": "hydrostatic_equilibrium", "optimization": "energy_balance",
        "fixed_points": "main_sequence_star",
        "operators": ["differential", "integrate", "balance"],
        "patterns": ["hydrostatic_equilibrium", "energy_transport", "compositional_structure"],
        "variables": {"state": "pressure", "mass": "enclosed_mass", "energy": "luminosity"},
        "conservation": ["mass", "energy"], "structure": "coupled_odes",
    },
    "black_hole_thermodynamics": {
        "id": "black_hole_thermodynamics", "name": "Black Hole Thermodynamics", "domain": "Astrophysics",
        "equation": "dM = (κ/8π) dA + Ω dJ + Φ dQ",
        "update_form": "horizon_dynamics", "optimization": "maximize_entropy",
        "fixed_points": "extremal_black_hole",
        "operators": ["surface_gravity", "area_increase", "first_law"],
        "patterns": ["entropy_maximization", "thermodynamic_law", "holographic_principle"],
        "variables": {"state": "mass", "temperature": "surface_gravity", "entropy": "horizon_area"},
        "conservation": ["energy", "angular_momentum", "charge"], "structure": "thermodynamic_relations",
    },
    "dark_matter_halo": {
        "id": "dark_matter_halo", "name": "NFW Dark Matter Halo Profile", "domain": "Astrophysics",
        "equation": "ρ(r) = ρ₀ / [(r/r_s)(1 + r/r_s)²]",
        "update_form": "gravitational_collapse", "optimization": "virialize",
        "fixed_points": "virial_equilibrium",
        "operators": ["radial_profile", "integrate_mass", "scale"],
        "patterns": ["scale_invariance", "power_law", "gravitational_clustering"],
        "variables": {"state": "density_profile", "scale": "halo_radius", "concentration": "c_param"},
        "conservation": ["mass"], "structure": "self_similar_profile",
    },
    "cmb_anisotropy": {
        "id": "cmb_anisotropy", "name": "CMB Anisotropy Spectrum", "domain": "Astrophysics",
        "equation": "C_ℓ = ⟨|a_ℓm|²⟩",
        "update_form": "perturbation_evolution", "optimization": "match_observed_spectrum",
        "fixed_points": "primordial_power_spectrum",
        "operators": ["spherical_harmonic", "ensemble_average", "transfer_function"],
        "patterns": ["acoustic_oscillation", "harmonic_decomposition", "primordial_signal"],
        "variables": {"state": "temperature_fluctuation", "scale": "multipole", "primordial": "inflation_potential"},
        "conservation": ["statistical_isotropy"], "structure": "power_spectrum",
    },
    "stellar_nucleosynthesis": {
        "id": "stellar_nucleosynthesis", "name": "Stellar Nucleosynthesis", "domain": "Astrophysics",
        "equation": "dN_A/dt = Σ N_B N_C ⟨σv⟩_BC→A",
        "update_form": "reaction_network", "optimization": "energy_yield",
        "fixed_points": "iron_peak_equilibrium",
        "operators": ["reaction_rate", "cross_section", "boltzmann_integrate"],
        "patterns": ["reaction_network", "chain_dynamics", "energy_release"],
        "variables": {"state": "isotope_abundance", "rate": "reaction_rate", "temperature": "core_temp"},
        "conservation": ["baryon_number"], "structure": "coupled_kinetic_equations",
    },
    "gravitational_waves": {
        "id": "gravitational_waves", "name": "Gravitational Wave Propagation", "domain": "Astrophysics",
        "equation": "□h_μν = -16πG T_μν",
        "update_form": "wave_equation", "optimization": "detect_strain",
        "fixed_points": "vacuum_propagation",
        "operators": ["dalembertian", "polarize", "transverse_traceless_gauge"],
        "patterns": ["wave_propagation", "linearized_dynamics", "transverse_polarization"],
        "variables": {"state": "metric_perturbation", "source": "stress_energy", "polarization": "plus_cross"},
        "conservation": ["wave_energy"], "structure": "linearized_einstein_equations",
    },
    "dark_energy_quintessence": {
        "id": "dark_energy_quintessence", "name": "Quintessence Dark Energy", "domain": "Astrophysics",
        "equation": "φ̈ + 3Hφ̇ + V'(φ) = 0",
        "update_form": "scalar_field_evolution", "optimization": "explain_acceleration",
        "fixed_points": "slow_roll_attractor",
        "operators": ["covariant_derivative", "potential_gradient", "hubble_friction"],
        "patterns": ["scalar_field", "slow_roll", "tracking_solution"],
        "variables": {"state": "scalar_field", "potential": "field_potential", "expansion": "hubble_rate"},
        "conservation": ["stress_energy"], "structure": "klein_gordon_on_frw",
    },

    # ── Chemistry (8) ──
    "chemical_equilibrium": {
        "id": "chemical_equilibrium", "name": "Chemical Equilibrium / Le Chatelier", "domain": "Chemistry",
        "equation": "K_eq = Π [products]^ν / Π [reactants]^ν",
        "update_form": "mass_action_kinetics", "optimization": "minimize_gibbs_energy",
        "fixed_points": "equilibrium_constant",
        "operators": ["product", "ratio", "exponentiate"],
        "patterns": ["equilibrium", "energy_minimization", "mass_action"],
        "variables": {"state": "concentration", "energy": "gibbs_free", "constant": "equilibrium_K"},
        "conservation": ["mass", "energy"], "structure": "thermodynamic_equilibrium",
    },
    "arrhenius_kinetics": {
        "id": "arrhenius_kinetics", "name": "Arrhenius Reaction Kinetics", "domain": "Chemistry",
        "equation": "k = A exp(-E_a / RT)",
        "update_form": "rate_law", "optimization": "minimize_activation_energy",
        "fixed_points": "barrier_crossing_rate",
        "operators": ["exponentiate", "boltzmann_factor"],
        "patterns": ["exponential_family", "energy_based", "thermal_activation"],
        "variables": {"state": "reaction_rate", "energy": "activation_barrier", "temperature": "kinetic_temp"},
        "conservation": ["activation_energy"], "structure": "transition_state_theory",
    },
    "michaelis_menten": {
        "id": "michaelis_menten", "name": "Michaelis-Menten Enzyme Kinetics", "domain": "Chemistry",
        "equation": "v = V_max [S] / (K_M + [S])",
        "update_form": "saturable_kinetics", "optimization": "catalytic_efficiency",
        "fixed_points": "enzyme_substrate_complex",
        "operators": ["bind", "catalyze", "saturate"],
        "patterns": ["saturation", "rate_limiting", "binding_kinetics"],
        "variables": {"state": "enzyme_complex", "substrate": "concentration", "rate": "velocity"},
        "conservation": ["enzyme_total"], "structure": "rational_function",
    },
    "molecular_orbital": {
        "id": "molecular_orbital", "name": "Molecular Orbital Theory (LCAO)", "domain": "Chemistry",
        "equation": "ψ_MO = Σ c_i φ_i",
        "update_form": "linear_combination", "optimization": "variational_energy",
        "fixed_points": "ground_state_orbital",
        "operators": ["linear_combine", "diagonalize", "overlap_integral"],
        "patterns": ["superposition", "variational_principle", "eigenvalue_problem"],
        "variables": {"state": "molecular_orbital", "basis": "atomic_orbitals", "energy": "orbital_energy"},
        "conservation": ["electron_count"], "structure": "hilbert_space_decomposition",
    },
    "free_radical_polymerization": {
        "id": "free_radical_polymerization", "name": "Free Radical Polymerization", "domain": "Chemistry",
        "equation": "dM/dt = -k_p [M·][M]",
        "update_form": "chain_kinetics", "optimization": "polymer_chain_growth",
        "fixed_points": "termination",
        "operators": ["initiate", "propagate", "terminate"],
        "patterns": ["chain_reaction", "branching_process", "stochastic_growth"],
        "variables": {"state": "polymer_chain", "radical": "active_center", "monomer": "concentration"},
        "conservation": ["chain_carrier"], "structure": "branching_kinetics",
    },
    "hard_soft_acid_base": {
        "id": "hard_soft_acid_base", "name": "HSAB Theory (Pearson)", "domain": "Chemistry",
        "equation": "ΔG = (χ_A - χ_B)² + (η_A + η_B)/2",
        "update_form": "electronegativity_matching", "optimization": "stability_pairing",
        "fixed_points": "preferred_complexation",
        "operators": ["match_hardness", "polarize", "form_complex"],
        "patterns": ["matching_principle", "energy_minimization", "dual_classification"],
        "variables": {"state": "complex", "acid": "lewis_acid", "base": "lewis_base"},
        "conservation": ["electron_pair"], "structure": "classification_rule",
    },
    "marcus_theory": {
        "id": "marcus_theory", "name": "Marcus Electron Transfer Theory", "domain": "Chemistry",
        "equation": "k_ET = (2π/ℏ)|H_DA|² (4πλk_BT)^{-1/2} exp(-(ΔG° + λ)²/4λk_BT)",
        "update_form": "tunneling_rate", "optimization": "minimize_reorganization_energy",
        "fixed_points": "inverted_region_maximum",
        "operators": ["quantum_tunnel", "gaussian_integrate", "couple"],
        "patterns": ["exponential_family", "quadratic_dependence", "barrier_crossing"],
        "variables": {"state": "electron_position", "energy": "reorganization", "coupling": "donor_acceptor"},
        "conservation": ["total_energy"], "structure": "rate_theory",
    },
    "supramolecular_self_assembly": {
        "id": "supramolecular_self_assembly", "name": "Supramolecular Self-Assembly", "domain": "Chemistry",
        "equation": "ΔG_assembly = ΔH - TΔS",
        "update_form": "non_covalent_interaction", "optimization": "free_energy_minimization",
        "fixed_points": "equilibrium_structure",
        "operators": ["hydrogen_bond", "stack", "host_guest_bind"],
        "patterns": ["self_organization", "energy_entropy_tradeoff", "emergent_structure"],
        "variables": {"state": "assembled_complex", "components": "molecular_units", "interaction": "non_covalent"},
        "conservation": ["component_count"], "structure": "thermodynamic_self_assembly",
    },

    # ── Linguistics / NLP (8) ──
    "transformer_attention": {
        "id": "transformer_attention", "name": "Transformer / Self-Attention", "domain": "Linguistics",
        "equation": "Attention(Q,K,V) = softmax(QK^T/√d_k)V",
        "update_form": "attention_computation", "optimization": "minimize_lm_loss",
        "fixed_points": "context_aware_representation",
        "operators": ["dot_product", "softmax", "weighted_sum", "matrix_product"],
        "patterns": ["attention_mechanism", "soft_routing", "compositional_structure"],
        "variables": {"state": "token_embedding", "query": "query_vector", "key_value": "key_value_pairs"},
        "conservation": ["softmax_sum"], "structure": "attention_layer",
    },
    "word2vec": {
        "id": "word2vec", "name": "Word2Vec / Skip-Gram", "domain": "Linguistics",
        "equation": "P(w_O | w_I) = exp(v_O · v_I) / Σ exp(v · v_I)",
        "update_form": "negative_sampling_gradient", "optimization": "maximize_context_probability",
        "fixed_points": "distributed_representation",
        "operators": ["dot_product", "softmax", "sample_negatives"],
        "patterns": ["distributional_semantics", "exponential_family", "embedding_learning"],
        "variables": {"state": "word_vector", "context": "co_occurring_words", "target": "center_word"},
        "conservation": ["vocabulary_coverage"], "structure": "shallow_neural_network",
    },
    "n_gram_model": {
        "id": "n_gram_model", "name": "N-gram Language Model", "domain": "Linguistics",
        "equation": "P(w_n | w_{n-1},...,w_{n-N+1}) = C(w_{n-N+1:n}) / C(w_{n-N+1:n-1})",
        "update_form": "frequency_counting", "optimization": "maximize_likelihood",
        "fixed_points": "smoothed_distribution",
        "operators": ["count", "normalize", "smooth"],
        "patterns": ["frequency_estimation", "markov_assumption", "conditional_probability"],
        "variables": {"state": "word_sequence", "context": "previous_words", "distribution": "next_word_prob"},
        "conservation": ["probability_normalization"], "structure": "conditional_distribution",
    },
    "syntax_parsing": {
        "id": "syntax_parsing", "name": "Chomsky Hierarchy / Syntactic Parsing", "domain": "Linguistics",
        "equation": "S → NP VP,  VP → V NP, ...",
        "update_form": "rule_application", "optimization": "valid_parse_tree",
        "fixed_points": "grammatical_sentence",
        "operators": ["produce", "rewrite", "match_pattern"],
        "patterns": ["compositional_structure", "recursive_decomposition", "formal_grammar"],
        "variables": {"state": "parse_tree", "rule": "production_rule", "symbol": "terminal_nonterminal"},
        "conservation": ["grammar_rules"], "structure": "context_free_grammar",
    },
    "tf_idf": {
        "id": "tf_idf", "name": "TF-IDF Term Weighting", "domain": "Linguistics",
        "equation": "tfidf(t,d) = tf(t,d) · log(N/df(t))",
        "update_form": "frequency_inverse_weighting", "optimization": "discriminate_terms",
        "fixed_points": "informative_weighting",
        "operators": ["count", "log", "inverse"],
        "patterns": ["information_weighting", "log_scaling", "discriminative_features"],
        "variables": {"state": "term_weight", "frequency": "term_frequency", "document_freq": "df"},
        "conservation": ["document_count"], "structure": "weighted_features",
    },
    "edit_distance": {
        "id": "edit_distance", "name": "Levenshtein / Edit Distance", "domain": "Linguistics",
        "equation": "d(i,j) = min[d(i-1,j)+1, d(i,j-1)+1, d(i-1,j-1)+δ(a_i,b_j)]",
        "update_form": "dynamic_programming", "optimization": "minimize_edits",
        "fixed_points": "optimal_alignment",
        "operators": ["insert", "delete", "substitute", "min"],
        "patterns": ["recursive_decomposition", "dynamic_programming", "metric_distance"],
        "variables": {"state": "edit_count", "sequence_a": "string_a", "sequence_b": "string_b"},
        "conservation": ["string_length_relation"], "structure": "dp_table",
    },
    "topic_modeling_lda": {
        "id": "topic_modeling_lda", "name": "Latent Dirichlet Allocation (LDA)", "domain": "Linguistics",
        "equation": "p(w,z,θ,φ | α,β) = p(θ|α)p(φ|β)Π p(z|θ)p(w|z,φ)",
        "update_form": "variational_em", "optimization": "maximize_data_likelihood",
        "fixed_points": "topic_word_distributions",
        "operators": ["dirichlet_sample", "categorical_sample", "marginalize"],
        "patterns": ["bayesian_inference", "latent_variable", "mixture_model"],
        "variables": {"state": "topic_distribution", "word": "observed", "topic": "latent_assignment"},
        "conservation": ["probability_simplex"], "structure": "hierarchical_bayes",
    },
    "constituency_grammar": {
        "id": "constituency_grammar", "name": "Constituency Grammar / PCFG", "domain": "Linguistics",
        "equation": "P(T) = Π P(rule_i)",
        "update_form": "probabilistic_rule_application", "optimization": "max_likelihood_tree",
        "fixed_points": "most_probable_parse",
        "operators": ["rule_apply", "multiply_prob", "viterbi"],
        "patterns": ["compositional_structure", "probabilistic_rules", "hierarchical_structure"],
        "variables": {"state": "parse_tree", "rule": "production", "probability": "rule_prob"},
        "conservation": ["probability_per_nonterminal"], "structure": "probabilistic_grammar",
    },

    # ── Bioinformatics (6) ──
    "blast_alignment": {
        "id": "blast_alignment", "name": "BLAST Sequence Alignment", "domain": "Bioinformatics",
        "equation": "E = K·m·n·exp(-λS)",
        "update_form": "heuristic_seed_extend", "optimization": "minimize_e_value",
        "fixed_points": "high_scoring_pair",
        "operators": ["seed", "extend", "score"],
        "patterns": ["heuristic_search", "exponential_family", "local_alignment"],
        "variables": {"state": "alignment", "score": "raw_score", "significance": "e_value"},
        "conservation": ["sequence_identity"], "structure": "alignment_algorithm",
    },
    "hidden_markov_genomics": {
        "id": "hidden_markov_genomics", "name": "HMM for Gene Finding", "domain": "Bioinformatics",
        "equation": "P(O,Q | λ) = Π a_{q_{t-1}q_t} b_{q_t}(o_t)",
        "update_form": "viterbi_baum_welch", "optimization": "maximum_likelihood_path",
        "fixed_points": "most_likely_state_sequence",
        "operators": ["transition", "emit", "viterbi", "forward_backward"],
        "patterns": ["markov_property", "latent_variable", "dynamic_programming"],
        "variables": {"state": "gene_structure", "observation": "nucleotide_sequence", "latent": "gene_state"},
        "conservation": ["transition_probability"], "structure": "hmm",
    },
    "phylogenetic_tree": {
        "id": "phylogenetic_tree", "name": "Phylogenetic Tree Inference", "domain": "Bioinformatics",
        "equation": "L = Π P(x_i | tree, μ)",
        "update_form": "maximum_likelihood_tree", "optimization": "best_tree_topology",
        "fixed_points": "ml_tree",
        "operators": ["mutate", "tree_search", "likelihood_eval"],
        "patterns": ["tree_structure", "evolutionary_distance", "maximum_likelihood"],
        "variables": {"state": "tree_topology", "branch": "evolutionary_distance", "site": "sequence_position"},
        "conservation": ["evolutionary_history"], "structure": "tree_model",
    },
    "protein_folding": {
        "id": "protein_folding", "name": "Protein Folding (Anfinsen)", "domain": "Bioinformatics",
        "equation": "structure* = argmin_s E(s, sequence)",
        "update_form": "energy_minimization", "optimization": "minimize_free_energy",
        "fixed_points": "native_state",
        "operators": ["fold", "minimize_energy", "explore_conformation"],
        "patterns": ["energy_based", "energy_minimization", "structural_self_assembly"],
        "variables": {"state": "protein_conformation", "energy": "free_energy", "sequence": "amino_acid"},
        "conservation": ["mass", "covalent_bonds"], "structure": "energy_landscape",
    },
    "alphafold_msa": {
        "id": "alphafold_msa", "name": "AlphaFold (Evoformer)", "domain": "Bioinformatics",
        "equation": "P(structure | sequence, MSA) via attention",
        "update_form": "attention_based_inference", "optimization": "predict_3d_structure",
        "fixed_points": "predicted_structure",
        "operators": ["attend_msa", "pair_representation", "structure_module"],
        "patterns": ["attention_mechanism", "coevolution", "structure_prediction"],
        "variables": {"state": "atomic_coordinates", "msa": "multiple_alignment", "pair": "residue_pair"},
        "conservation": ["geometric_constraints"], "structure": "deep_attention_network",
    },
    "gwas": {
        "id": "gwas", "name": "Genome-Wide Association Study (GWAS)", "domain": "Bioinformatics",
        "equation": "y = Xβ + ε,  test H₀: β_j = 0",
        "update_form": "marginal_regression", "optimization": "identify_significant_loci",
        "fixed_points": "associated_snps",
        "operators": ["regress", "test", "bonferroni_correct"],
        "patterns": ["multiple_testing", "linear_regression", "association_signal"],
        "variables": {"state": "phenotype", "snp": "genotype", "effect": "beta_coefficient"},
        "conservation": ["family_wise_error"], "structure": "marginal_tests",
    },

    # ── Cryptography (6) ──
    "rsa_cryptosystem": {
        "id": "rsa_cryptosystem", "name": "RSA Cryptosystem", "domain": "Cryptography",
        "equation": "c = m^e mod n,  m = c^d mod n",
        "update_form": "modular_exponentiation", "optimization": "factoring_hardness",
        "fixed_points": "encrypted_decrypted_pair",
        "operators": ["modular_exp", "prime_generate", "extended_euclidean"],
        "patterns": ["one_way_function", "trapdoor_function", "modular_arithmetic"],
        "variables": {"state": "message", "key_pub": "public_key", "key_priv": "private_key"},
        "conservation": ["totient"], "structure": "trapdoor_permutation",
    },
    "diffie_hellman": {
        "id": "diffie_hellman", "name": "Diffie-Hellman Key Exchange", "domain": "Cryptography",
        "equation": "K = g^{ab} mod p",
        "update_form": "discrete_log_hardness", "optimization": "shared_secret",
        "fixed_points": "agreed_key",
        "operators": ["modular_exp", "exchange", "compute_shared"],
        "patterns": ["one_way_function", "shared_computation", "discrete_log"],
        "variables": {"state": "shared_secret", "generator": "g", "private": "exponent"},
        "conservation": ["group_structure"], "structure": "group_based_protocol",
    },
    "zero_knowledge_proof": {
        "id": "zero_knowledge_proof", "name": "Zero-Knowledge Proof", "domain": "Cryptography",
        "equation": "P(verifier accepts | witness=true) = 1, no info leaked",
        "update_form": "challenge_response", "optimization": "preserve_witness_secrecy",
        "fixed_points": "verified_statement",
        "operators": ["commit", "challenge", "respond", "verify"],
        "patterns": ["interactive_protocol", "information_hiding", "completeness_soundness"],
        "variables": {"state": "statement", "witness": "secret_proof", "transcript": "interaction"},
        "conservation": ["zero_knowledge_property"], "structure": "interactive_proof",
    },
    "merkle_tree": {
        "id": "merkle_tree", "name": "Merkle Tree", "domain": "Cryptography",
        "equation": "root = H(H(H(d₁,d₂), H(d₃,d₄)), ...)",
        "update_form": "recursive_hash", "optimization": "efficient_membership_proof",
        "fixed_points": "root_hash",
        "operators": ["hash", "concatenate", "tree_walk"],
        "patterns": ["recursive_structure", "binding_commitment", "logarithmic_proof"],
        "variables": {"state": "root_hash", "leaf": "data_block", "path": "merkle_path"},
        "conservation": ["collision_resistance"], "structure": "binary_hash_tree",
    },
    "lattice_cryptography": {
        "id": "lattice_cryptography", "name": "Lattice-Based Cryptography (LWE)", "domain": "Cryptography",
        "equation": "b = As + e mod q,  solve for s",
        "update_form": "noisy_linear_algebra", "optimization": "lwe_hardness",
        "fixed_points": "indistinguishability",
        "operators": ["matrix_mult", "add_noise", "round"],
        "patterns": ["noisy_inference", "computational_hardness", "lattice_structure"],
        "variables": {"state": "secret_vector", "matrix": "public_matrix", "noise": "error_term"},
        "conservation": ["lattice_lattice"], "structure": "lattice_problem",
    },
    "blockchain_consensus": {
        "id": "blockchain_consensus", "name": "Proof-of-Work / Nakamoto Consensus", "domain": "Cryptography",
        "equation": "find n: H(block || n) < target",
        "update_form": "puzzle_solving", "optimization": "longest_valid_chain",
        "fixed_points": "consensus_chain",
        "operators": ["hash", "increment_nonce", "broadcast"],
        "patterns": ["proof_of_work", "consensus", "fork_choice"],
        "variables": {"state": "blockchain", "puzzle": "hash_target", "block": "candidate"},
        "conservation": ["longest_chain_rule"], "structure": "byzantine_fault_tolerant_protocol",
    },

    # ── Complex Systems (6) ──
    "cellular_automata": {
        "id": "cellular_automata", "name": "Cellular Automata / Game of Life", "domain": "Complex Systems",
        "equation": "x_i^{t+1} = f(x_{i-1}^t, x_i^t, x_{i+1}^t)",
        "update_form": "local_rule_update", "optimization": "emergent_patterns",
        "fixed_points": "stable_configuration",
        "operators": ["local_rule", "discrete_update", "neighborhood"],
        "patterns": ["local_interaction", "emergence", "discrete_dynamics"],
        "variables": {"state": "cell_state", "neighborhood": "local_pattern", "rule": "transition_function"},
        "conservation": ["cell_count_in_period"], "structure": "discrete_dynamical_system",
    },
    "small_world": {
        "id": "small_world", "name": "Watts-Strogatz Small World", "domain": "Complex Systems",
        "equation": "L ~ log(N),  C >> C_random",
        "update_form": "rewire_with_probability", "optimization": "balance_clustering_pathlength",
        "fixed_points": "small_world_regime",
        "operators": ["rewire", "measure_path", "measure_clustering"],
        "patterns": ["network_topology", "phase_transition", "scale_separation"],
        "variables": {"state": "graph", "rewire_prob": "p", "structure": "clustering_coefficient"},
        "conservation": ["edge_count"], "structure": "network_model",
    },
    "agent_based_model": {
        "id": "agent_based_model", "name": "Agent-Based Modeling", "domain": "Complex Systems",
        "equation": "state_i^{t+1} = update(state_i^t, neighbors_i^t, env^t)",
        "update_form": "agent_local_update", "optimization": "emergent_behavior",
        "fixed_points": "macro_pattern",
        "operators": ["agent_step", "interact", "aggregate"],
        "patterns": ["emergence", "local_interaction", "heterogeneous_agents"],
        "variables": {"state": "agent_state", "rules": "behavior", "environment": "context"},
        "conservation": ["agent_count"], "structure": "multi_agent_simulation",
    },
    "tipping_points": {
        "id": "tipping_points", "name": "Tipping Points / Critical Transitions", "domain": "Complex Systems",
        "equation": "dx/dt = f(x,r),  bifurcation at r_c",
        "update_form": "slow_fast_dynamics", "optimization": "detect_warning_signals",
        "fixed_points": "alternative_stable_states",
        "operators": ["bifurcate", "perturb", "measure_variance"],
        "patterns": ["phase_transition", "critical_slowing_down", "hysteresis"],
        "variables": {"state": "system_state", "parameter": "control_param", "noise": "perturbation"},
        "conservation": ["topology_of_attractors"], "structure": "bifurcation_dynamics",
    },
    "power_law_distribution": {
        "id": "power_law_distribution", "name": "Power Law / Pareto Distribution", "domain": "Complex Systems",
        "equation": "P(x) ~ x^{-α}",
        "update_form": "preferential_growth", "optimization": "scale_free_distribution",
        "fixed_points": "heavy_tailed_stable",
        "operators": ["power", "rank", "log_log_fit"],
        "patterns": ["scale_invariance", "heavy_tail", "rich_get_richer"],
        "variables": {"state": "rank_distribution", "exponent": "alpha", "support": "x_min"},
        "conservation": ["total_quantity"], "structure": "heavy_tailed_distribution",
    },
    "synchronization_kuramoto": {
        "id": "synchronization_kuramoto", "name": "Kuramoto Oscillator Synchronization", "domain": "Complex Systems",
        "equation": "dθ_i/dt = ω_i + (K/N) Σⱼ sin(θⱼ - θᵢ)",
        "update_form": "coupled_phase_evolution", "optimization": "phase_coherence",
        "fixed_points": "synchronized_state",
        "operators": ["couple", "sum_sin_phases", "phase_average"],
        "patterns": ["synchronization", "phase_transition", "mean_field"],
        "variables": {"state": "oscillator_phase", "coupling": "K", "frequency": "natural_freq"},
        "conservation": ["mean_phase_velocity"], "structure": "coupled_oscillators",
    },

    # ── Sociology (6) ──
    "schelling_segregation": {
        "id": "schelling_segregation", "name": "Schelling Segregation Model", "domain": "Sociology",
        "equation": "agent moves if fraction_similar_neighbors < threshold",
        "update_form": "tolerance_threshold_move", "optimization": "satisfy_individual_preferences",
        "fixed_points": "segregated_equilibrium",
        "operators": ["count_neighbors", "compare_threshold", "relocate"],
        "patterns": ["emergence", "local_interaction", "threshold_dynamics"],
        "variables": {"state": "spatial_arrangement", "type": "agent_type", "tolerance": "similarity_threshold"},
        "conservation": ["agent_population"], "structure": "agent_based_segregation",
    },
    "diffusion_of_innovation": {
        "id": "diffusion_of_innovation", "name": "Rogers' Diffusion of Innovations", "domain": "Sociology",
        "equation": "dN/dt = (p + qN/M)(M - N)",
        "update_form": "bass_diffusion", "optimization": "fit_adoption_curve",
        "fixed_points": "saturation",
        "operators": ["external_influence", "imitate", "saturate"],
        "patterns": ["s_curve", "contagion", "innovator_imitator"],
        "variables": {"state": "adopters", "innovation_coef": "p", "imitation_coef": "q"},
        "conservation": ["market_potential"], "structure": "adoption_dynamics",
    },
    "homophily": {
        "id": "homophily", "name": "Homophily in Networks", "domain": "Sociology",
        "equation": "P(edge | same_type) > P(edge | different_type)",
        "update_form": "similarity_attachment", "optimization": "minimize_cross_type_edges",
        "fixed_points": "assortative_network",
        "operators": ["measure_similarity", "form_edge", "assort"],
        "patterns": ["assortativity", "selection_effect", "social_influence"],
        "variables": {"state": "social_network", "attribute": "agent_type", "tie_strength": "edge_weight"},
        "conservation": ["network_size"], "structure": "assortative_mixing",
    },
    "weak_ties": {
        "id": "weak_ties", "name": "Granovetter's Strength of Weak Ties", "domain": "Sociology",
        "equation": "info_diffusion ~ 1/strength_of_tie",
        "update_form": "bridge_dependent_flow", "optimization": "information_reach",
        "fixed_points": "bridging_role",
        "operators": ["bridge", "diffuse", "measure_tie_strength"],
        "patterns": ["information_flow", "structural_role", "betweenness"],
        "variables": {"state": "information", "tie": "edge_strength", "bridge": "betweenness_node"},
        "conservation": ["graph_connectivity"], "structure": "social_network_flow",
    },
    "social_capital": {
        "id": "social_capital", "name": "Social Capital / Bourdieu", "domain": "Sociology",
        "equation": "outcome = f(economic, social, cultural capital)",
        "update_form": "capital_accumulation", "optimization": "convert_between_capitals",
        "fixed_points": "stratified_society",
        "operators": ["accumulate", "convert", "deploy"],
        "patterns": ["resource_accumulation", "multi_dimensional_capital", "stratification"],
        "variables": {"state": "capital_stock", "type": "capital_form", "agent": "individual"},
        "conservation": ["total_field_capital"], "structure": "multi_resource_accumulation",
    },
    "collective_action": {
        "id": "collective_action", "name": "Olson's Logic of Collective Action", "domain": "Sociology",
        "equation": "rational_contribute if private_benefit > cost",
        "update_form": "rational_choice", "optimization": "individual_payoff",
        "fixed_points": "free_rider_equilibrium",
        "operators": ["compute_benefit", "free_ride", "coordinate"],
        "patterns": ["free_rider_problem", "public_good", "coordination_failure"],
        "variables": {"state": "contribution_level", "benefit": "shared_good", "cost": "individual_cost"},
        "conservation": ["aggregate_payoff"], "structure": "public_goods_game",
    },

    # ── Behavioral Economics (6) ──
    "prospect_theory": {
        "id": "prospect_theory", "name": "Prospect Theory (Kahneman-Tversky)", "domain": "Behavioral Economics",
        "equation": "V = Σ π(p_i) · v(x_i),  v concave in gains, convex in losses",
        "update_form": "reference_dependent_eval", "optimization": "subjective_value",
        "fixed_points": "decision_outcome",
        "operators": ["weight_probability", "evaluate_relative", "asymmetric_value"],
        "patterns": ["reference_dependence", "loss_aversion", "probability_weighting"],
        "variables": {"state": "decision", "reference": "status_quo", "outcome": "gain_loss"},
        "conservation": ["preference_consistency"], "structure": "non_linear_utility",
    },
    "hyperbolic_discounting": {
        "id": "hyperbolic_discounting", "name": "Hyperbolic Discounting", "domain": "Behavioral Economics",
        "equation": "PV = V / (1 + kt)",
        "update_form": "time_inconsistent", "optimization": "present_biased_choice",
        "fixed_points": "preference_reversal",
        "operators": ["discount", "time_compare", "reverse_preference"],
        "patterns": ["time_inconsistency", "present_bias", "non_exponential_decay"],
        "variables": {"state": "future_value", "delay": "time_lag", "discount_rate": "k"},
        "conservation": ["preference_at_each_time"], "structure": "time_preference_model",
    },
    "anchoring_bias": {
        "id": "anchoring_bias", "name": "Anchoring and Adjustment", "domain": "Behavioral Economics",
        "equation": "estimate = anchor + adjustment",
        "update_form": "insufficient_adjustment", "optimization": "minimize_cognitive_effort",
        "fixed_points": "anchor_biased_estimate",
        "operators": ["anchor", "adjust_partially", "bias"],
        "patterns": ["cognitive_heuristic", "starting_point_bias", "insufficient_correction"],
        "variables": {"state": "estimate", "anchor": "initial_value", "adjustment": "deviation"},
        "conservation": ["anchor_influence"], "structure": "heuristic_estimation",
    },
    "nudge_theory": {
        "id": "nudge_theory", "name": "Nudge / Choice Architecture", "domain": "Behavioral Economics",
        "equation": "behavior = f(default, framing, salience)",
        "update_form": "default_preserving", "optimization": "guide_choice_without_force",
        "fixed_points": "altered_default_behavior",
        "operators": ["set_default", "frame_choice", "reduce_friction"],
        "patterns": ["status_quo_bias", "framing_effect", "behavioral_intervention"],
        "variables": {"state": "behavior", "architecture": "choice_design", "default": "baseline_option"},
        "conservation": ["formal_freedom_of_choice"], "structure": "behavioral_intervention",
    },
    "herd_behavior": {
        "id": "herd_behavior", "name": "Information Cascades / Herd Behavior", "domain": "Behavioral Economics",
        "equation": "P(act_t | signals_{1:t-1}) > P(act_t | private_signal_t)",
        "update_form": "social_information_dominance", "optimization": "imitate_predecessors",
        "fixed_points": "cascade_state",
        "operators": ["observe_others", "ignore_private", "follow"],
        "patterns": ["information_aggregation_failure", "social_learning", "cascade"],
        "variables": {"state": "action", "private_signal": "info", "public_history": "observed_actions"},
        "conservation": ["aggregate_action_history"], "structure": "sequential_decision_model",
    },
    "endowment_effect": {
        "id": "endowment_effect", "name": "Endowment Effect / Status Quo Bias", "domain": "Behavioral Economics",
        "equation": "WTA > WTP",
        "update_form": "ownership_premium", "optimization": "loss_aversion_pricing",
        "fixed_points": "trade_resistance",
        "operators": ["evaluate_owned", "evaluate_unowned", "compare_asymmetric"],
        "patterns": ["loss_aversion", "reference_dependence", "status_quo"],
        "variables": {"state": "valuation", "owned": "endowment", "unowned": "not_owned"},
        "conservation": ["object_intrinsic_value"], "structure": "asymmetric_valuation",
    },

    # ── Decision Theory (6) ──
    "expected_utility": {
        "id": "expected_utility", "name": "Expected Utility Theory (vNM)", "domain": "Decision Theory",
        "equation": "EU = Σ p_i · u(x_i)",
        "update_form": "linear_expectation", "optimization": "maximize_expected_utility",
        "fixed_points": "rational_choice",
        "operators": ["weight_probability", "sum_utility", "maximize"],
        "patterns": ["probability_weighted", "linearity_in_probabilities", "rational_choice"],
        "variables": {"state": "lottery", "probability": "p", "utility": "u_function"},
        "conservation": ["preference_ordering"], "structure": "linear_utility_aggregation",
    },
    "minimax_decision": {
        "id": "minimax_decision", "name": "Minimax / Worst-Case Decision", "domain": "Decision Theory",
        "equation": "action* = argmin_a max_s loss(a,s)",
        "update_form": "adversarial_evaluation", "optimization": "minimize_worst_case",
        "fixed_points": "minimax_equilibrium",
        "operators": ["worst_case", "min", "robustify"],
        "patterns": ["robust_optimization", "adversarial", "pessimistic"],
        "variables": {"state": "action", "uncertainty": "worst_state", "loss": "regret"},
        "conservation": ["worst_case_bound"], "structure": "minimax_optimization",
    },
    "savage_subjective_prob": {
        "id": "savage_subjective_prob", "name": "Savage Subjective Probability", "domain": "Decision Theory",
        "equation": "preferences over acts ⇒ unique probability + utility",
        "update_form": "axiomatic_derivation", "optimization": "consistent_beliefs",
        "fixed_points": "coherent_preferences",
        "operators": ["compare_acts", "derive_probability", "derive_utility"],
        "patterns": ["axiomatic_foundation", "subjective_belief", "consistency"],
        "variables": {"state": "preference", "act": "decision", "state_of_world": "uncertainty"},
        "conservation": ["sure_thing_principle"], "structure": "axiomatic_decision",
    },
    "regret_minimization": {
        "id": "regret_minimization", "name": "Regret Minimization", "domain": "Decision Theory",
        "equation": "regret = max_a Σ u(a,s) - Σ u(a_actual,s)",
        "update_form": "no_regret_learning", "optimization": "minimize_external_regret",
        "fixed_points": "no_regret_strategy",
        "operators": ["compute_regret", "average_regret", "match_distribution"],
        "patterns": ["online_learning", "competitive_ratio", "no_regret"],
        "variables": {"state": "action_history", "best_fixed": "hindsight_optimal", "regret": "deficit"},
        "conservation": ["sublinear_regret_bound"], "structure": "online_decision",
    },
    "mvp_satisficing": {
        "id": "mvp_satisficing", "name": "Simon's Satisficing / Bounded Rationality", "domain": "Decision Theory",
        "equation": "choose first option ≥ aspiration_level",
        "update_form": "threshold_acceptance", "optimization": "good_enough",
        "fixed_points": "satisfactory_choice",
        "operators": ["sequential_search", "compare_threshold", "stop"],
        "patterns": ["bounded_rationality", "heuristic", "search_then_stop"],
        "variables": {"state": "candidate", "aspiration": "threshold", "search_cost": "time"},
        "conservation": ["resource_budget"], "structure": "bounded_search",
    },
    "multi_attribute_utility": {
        "id": "multi_attribute_utility", "name": "Multi-Attribute Utility Theory (MAUT)", "domain": "Decision Theory",
        "equation": "U(x) = Σ w_i · u_i(x_i)",
        "update_form": "weighted_aggregation", "optimization": "best_multi_criteria",
        "fixed_points": "pareto_optimal",
        "operators": ["weight", "aggregate", "scale_normalize"],
        "patterns": ["additive_decomposition", "weighted_sum", "multi_objective"],
        "variables": {"state": "alternative", "attributes": "criteria", "weights": "preferences"},
        "conservation": ["weight_sum"], "structure": "aggregated_utility",
    },

    # ── Operations Research (6) ──
    "linear_programming": {
        "id": "linear_programming", "name": "Linear Programming / Simplex", "domain": "Operations Research",
        "equation": "max c^T x s.t. Ax ≤ b, x ≥ 0",
        "update_form": "pivot_operations", "optimization": "linear_objective",
        "fixed_points": "vertex_optimal",
        "operators": ["pivot", "tableau", "compute_reduced_cost"],
        "patterns": ["linear_optimization", "polyhedral_geometry", "duality"],
        "variables": {"state": "feasible_point", "objective": "cost_vector", "constraint": "Ax_b"},
        "conservation": ["primal_dual_objective"], "structure": "polyhedral_optimization",
    },
    "integer_programming": {
        "id": "integer_programming", "name": "Integer Programming", "domain": "Operations Research",
        "equation": "max c^T x s.t. Ax ≤ b, x ∈ ℤ",
        "update_form": "branch_and_bound", "optimization": "integer_optimum",
        "fixed_points": "integer_optimal",
        "operators": ["branch", "bound", "prune", "cut"],
        "patterns": ["combinatorial_optimization", "tree_search", "relaxation"],
        "variables": {"state": "integer_solution", "relaxation": "lp_solution", "branching": "variable_split"},
        "conservation": ["dual_bound"], "structure": "branch_bound_tree",
    },
    "queueing_theory": {
        "id": "queueing_theory", "name": "Queueing Theory / M/M/1", "domain": "Operations Research",
        "equation": "L = ρ/(1-ρ),  W = 1/(μ-λ)",
        "update_form": "birth_death_process", "optimization": "minimize_wait_time",
        "fixed_points": "steady_state_distribution",
        "operators": ["arrive", "serve", "depart"],
        "patterns": ["markov_process", "steady_state", "little_law"],
        "variables": {"state": "queue_length", "arrival_rate": "lambda", "service_rate": "mu"},
        "conservation": ["customer_count"], "structure": "markov_chain",
    },
    "inventory_management": {
        "id": "inventory_management", "name": "EOQ / Economic Order Quantity", "domain": "Operations Research",
        "equation": "Q* = √(2DK/h)",
        "update_form": "order_when_below_reorder", "optimization": "minimize_total_cost",
        "fixed_points": "optimal_order_quantity",
        "operators": ["compute_cost", "derive_optimal", "reorder"],
        "patterns": ["periodic_review", "cost_balance", "square_root_formula"],
        "variables": {"state": "inventory_level", "demand": "D", "cost": "ordering_holding"},
        "conservation": ["stock_balance"], "structure": "cost_optimization",
    },
    "shortest_path_dijkstra": {
        "id": "shortest_path_dijkstra", "name": "Dijkstra's Shortest Path", "domain": "Operations Research",
        "equation": "d(v) = min_u [d(u) + w(u,v)]",
        "update_form": "relaxation_priority", "optimization": "minimize_path_distance",
        "fixed_points": "shortest_path_tree",
        "operators": ["relax", "extract_min", "update_neighbors"],
        "patterns": ["dynamic_programming", "greedy_search", "graph_traversal"],
        "variables": {"state": "distance", "graph": "weighted_edges", "predecessor": "parent_in_tree"},
        "conservation": ["triangle_inequality"], "structure": "priority_queue_search",
    },
    "assignment_problem": {
        "id": "assignment_problem", "name": "Assignment Problem / Hungarian Method", "domain": "Operations Research",
        "equation": "min Σ c_ij x_ij s.t. Σ_j x_ij = 1, Σ_i x_ij = 1",
        "update_form": "primal_dual_iteration", "optimization": "minimize_assignment_cost",
        "fixed_points": "optimal_bipartite_matching",
        "operators": ["reduce_matrix", "augment_path", "dual_update"],
        "patterns": ["bipartite_matching", "duality", "combinatorial_optimization"],
        "variables": {"state": "assignment", "cost": "c_ij", "dual": "potentials"},
        "conservation": ["assignment_constraint"], "structure": "bipartite_optimization",
    },

    # ── Expand Reinforcement Learning (7 new) ──
    "q_learning": {
        "id": "q_learning", "name": "Q-Learning", "domain": "Reinforcement Learning",
        "equation": "Q(s,a) ← Q(s,a) + α[r + γ max_a' Q(s',a') - Q(s,a)]",
        "update_form": "td_with_bootstrapping", "optimization": "maximize_action_value",
        "fixed_points": "optimal_q_function",
        "operators": ["bootstrap", "max_over_actions", "td_update"],
        "patterns": ["temporal_difference", "off_policy", "bootstrapping"],
        "variables": {"state": "state_action_value", "td_target": "r_plus_max_q", "policy": "epsilon_greedy"},
        "conservation": ["bellman_equation"], "structure": "value_iteration",
    },
    "ppo": {
        "id": "ppo", "name": "Proximal Policy Optimization (PPO)", "domain": "Reinforcement Learning",
        "equation": "L = min(r·Â, clip(r,1-ε,1+ε)·Â)",
        "update_form": "clipped_surrogate", "optimization": "trust_region_policy",
        "fixed_points": "improved_policy",
        "operators": ["compute_ratio", "clip", "advantage"],
        "patterns": ["policy_gradient", "trust_region", "clipping"],
        "variables": {"state": "policy_params", "advantage": "gae", "ratio": "importance_ratio"},
        "conservation": ["kl_divergence_bound"], "structure": "policy_gradient",
    },
    "actor_critic": {
        "id": "actor_critic", "name": "Actor-Critic Methods", "domain": "Reinforcement Learning",
        "equation": "∇J = E[∇log π(a|s) · (Q(s,a) - V(s))]",
        "update_form": "dual_network_update", "optimization": "policy_value_simultaneous",
        "fixed_points": "actor_critic_equilibrium",
        "operators": ["policy_gradient", "value_estimate", "advantage"],
        "patterns": ["dual_optimization", "policy_gradient", "variance_reduction"],
        "variables": {"state": "policy_value", "advantage": "td_error", "actor": "policy_net"},
        "conservation": ["policy_gradient_theorem"], "structure": "dual_network",
    },
    "dqn": {
        "id": "dqn", "name": "Deep Q-Network (DQN)", "domain": "Reinforcement Learning",
        "equation": "L = E[(r + γ max Q_target - Q(s,a;θ))²]",
        "update_form": "experience_replay_target_net", "optimization": "minimize_td_error",
        "fixed_points": "optimal_deep_q",
        "operators": ["replay_buffer", "target_network", "td_minimize"],
        "patterns": ["temporal_difference", "deep_function_approximation", "experience_replay"],
        "variables": {"state": "deep_q_params", "target": "frozen_target", "memory": "replay_buffer"},
        "conservation": ["bellman_equation"], "structure": "neural_network_value",
    },
    "ddpg": {
        "id": "ddpg", "name": "Deep Deterministic Policy Gradient", "domain": "Reinforcement Learning",
        "equation": "∇J = E[∇_a Q(s,a) · ∇_θ μ(s;θ)]",
        "update_form": "deterministic_chain_rule", "optimization": "continuous_action_value",
        "fixed_points": "deterministic_optimal",
        "operators": ["deterministic_action", "chain_rule_gradient", "target_smoothing"],
        "patterns": ["policy_gradient", "deterministic_policy", "continuous_control"],
        "variables": {"state": "actor_critic_params", "action": "deterministic", "noise": "exploration"},
        "conservation": ["deterministic_policy_gradient"], "structure": "actor_critic_continuous",
    },
    "soft_actor_critic": {
        "id": "soft_actor_critic", "name": "Soft Actor-Critic (SAC)", "domain": "Reinforcement Learning",
        "equation": "J = E[Q(s,a) + α H(π(·|s))]",
        "update_form": "maximum_entropy_rl", "optimization": "entropy_regularized_value",
        "fixed_points": "max_entropy_optimal",
        "operators": ["entropy_bonus", "soft_value", "reparameterize"],
        "patterns": ["entropy_regularization", "exploration_exploitation", "soft_optimization"],
        "variables": {"state": "policy_params", "temperature": "alpha", "entropy": "policy_entropy"},
        "conservation": ["soft_bellman_equation"], "structure": "stochastic_actor_critic",
    },
    "model_based_dreamer": {
        "id": "model_based_dreamer", "name": "Dreamer / Latent World Model", "domain": "Reinforcement Learning",
        "equation": "imagine: z_{t+1} ~ p(·|z_t,a_t),  policy trained on imagined trajectories",
        "update_form": "imagination_rollout", "optimization": "model_based_policy",
        "fixed_points": "consistent_world_model",
        "operators": ["encode", "imagine", "policy_in_latent"],
        "patterns": ["world_model", "latent_dynamics", "imagination"],
        "variables": {"state": "latent_state", "policy": "actor_in_latent", "model": "transition_model"},
        "conservation": ["model_consistency"], "structure": "latent_dynamics_model",
    },

    # ── Expand Evolutionary Game Theory (7 new) ──
    "moran_process": {
        "id": "moran_process", "name": "Moran Process", "domain": "Evolutionary Game Theory",
        "equation": "P(i→i+1) = (i/N)(N-i)/N · f_A/⟨f⟩",
        "update_form": "birth_death_process", "optimization": "fixation_probability",
        "fixed_points": "fixation_loss",
        "operators": ["birth", "death", "select_by_fitness"],
        "patterns": ["stochastic_evolution", "fixation_probability", "finite_population"],
        "variables": {"state": "type_count", "fitness": "selection_intensity", "population_size": "N"},
        "conservation": ["population_size"], "structure": "stochastic_markov_chain",
    },
    "fisher_evolutionary_theorem": {
        "id": "fisher_evolutionary_theorem", "name": "Fisher's Fundamental Theorem", "domain": "Evolutionary Game Theory",
        "equation": "dW̄/dt = Var(W)/W̄",
        "update_form": "selection_rate_equation", "optimization": "increase_mean_fitness",
        "fixed_points": "exhausted_variance",
        "operators": ["differential", "variance", "ratio"],
        "patterns": ["mean_field", "selection", "above_average_grows"],
        "variables": {"state": "trait_frequency", "fitness": "darwinian_fitness", "variance": "trait_var"},
        "conservation": ["total_probability"], "structure": "ode_mean_dynamics",
    },
    "evolutionary_dynamics_pairwise": {
        "id": "evolutionary_dynamics_pairwise", "name": "Pairwise Imitation Dynamics", "domain": "Evolutionary Game Theory",
        "equation": "rate_change ∝ probability_imitate · fitness_difference",
        "update_form": "pairwise_imitation", "optimization": "spread_higher_payoff",
        "fixed_points": "all_same_strategy",
        "operators": ["pair_sample", "compare", "imitate"],
        "patterns": ["imitation", "frequency_dependent", "evolutionary_dynamics"],
        "variables": {"state": "strategy_distribution", "imitation_rate": "beta", "payoff": "fitness"},
        "conservation": ["total_population"], "structure": "imitation_model",
    },
    "hawk_dove": {
        "id": "hawk_dove", "name": "Hawk-Dove Game", "domain": "Evolutionary Game Theory",
        "equation": "ESS: x_hawk* = V/C",
        "update_form": "frequency_dependent_payoff", "optimization": "evolutionary_stability",
        "fixed_points": "mixed_ess",
        "operators": ["compute_payoff_matrix", "find_ess", "frequency_track"],
        "patterns": ["frequency_dependent", "evolutionary_stability", "mixed_equilibrium"],
        "variables": {"state": "strategy_proportion", "value": "V", "cost": "C"},
        "conservation": ["population_normalization"], "structure": "2x2_game",
    },
    "kin_selection": {
        "id": "kin_selection", "name": "Hamilton's Rule / Kin Selection", "domain": "Evolutionary Game Theory",
        "equation": "rb > c",
        "update_form": "inclusive_fitness", "optimization": "maximize_inclusive_fitness",
        "fixed_points": "altruism_threshold",
        "operators": ["compute_relatedness", "weight_benefit", "compare"],
        "patterns": ["inclusive_fitness", "relatedness", "altruism"],
        "variables": {"state": "behavior", "relatedness": "r", "benefit_cost": "b_c"},
        "conservation": ["gene_propagation"], "structure": "inclusive_fitness_calculus",
    },
    "spatial_evolution": {
        "id": "spatial_evolution", "name": "Spatial Evolutionary Game", "domain": "Evolutionary Game Theory",
        "equation": "strategy spreads on a lattice with neighborhood payoff",
        "update_form": "local_imitation_update", "optimization": "cluster_cooperation",
        "fixed_points": "spatial_pattern",
        "operators": ["lattice_neighborhood", "compute_local_payoff", "update_strategy"],
        "patterns": ["spatial_structure", "clustering", "local_interaction"],
        "variables": {"state": "lattice_strategy", "neighborhood": "k_neighbors", "payoff": "local"},
        "conservation": ["lattice_topology"], "structure": "spatial_game",
    },
    "group_selection": {
        "id": "group_selection", "name": "Multilevel / Group Selection", "domain": "Evolutionary Game Theory",
        "equation": "Δx = Cov(W_group, x) + E[Cov(W_individual, x)]",
        "update_form": "price_decomposition", "optimization": "multilevel_fitness",
        "fixed_points": "between_within_balance",
        "operators": ["price_equation", "covariance", "decompose"],
        "patterns": ["multilevel_selection", "covariance_decomposition", "altruism"],
        "variables": {"state": "trait_frequency", "group": "subpopulation", "individual": "agent"},
        "conservation": ["price_identity"], "structure": "multilevel_decomposition",
    },

    # ── Expand Information Theory (6 new) ──
    "huffman_coding": {
        "id": "huffman_coding", "name": "Huffman Coding", "domain": "Information Theory",
        "equation": "code_length(x) ≈ -log P(x)",
        "update_form": "greedy_tree_construction", "optimization": "minimize_expected_length",
        "fixed_points": "optimal_prefix_code",
        "operators": ["merge_lowest_freq", "build_tree", "assign_code"],
        "patterns": ["entropy_coding", "tree_structure", "optimal_compression"],
        "variables": {"state": "code_tree", "probability": "p_x", "length": "code_bits"},
        "conservation": ["kraft_inequality"], "structure": "binary_tree_code",
    },
    "arithmetic_coding": {
        "id": "arithmetic_coding", "name": "Arithmetic Coding", "domain": "Information Theory",
        "equation": "encode message as interval [low, high] in [0,1]",
        "update_form": "interval_refinement", "optimization": "approach_entropy",
        "fixed_points": "shannon_limit",
        "operators": ["subdivide_interval", "rescale", "emit_bit"],
        "patterns": ["entropy_coding", "interval_arithmetic", "near_optimal_compression"],
        "variables": {"state": "interval", "probability": "context_model", "bits": "output_stream"},
        "conservation": ["interval_length_log"], "structure": "interval_coding",
    },
    "channel_capacity": {
        "id": "channel_capacity", "name": "Channel Capacity (Noisy Channel)", "domain": "Information Theory",
        "equation": "C = max_{p(x)} I(X;Y)",
        "update_form": "max_mutual_info", "optimization": "achievable_rate",
        "fixed_points": "shannon_capacity",
        "operators": ["mutual_information", "maximize", "channel_model"],
        "patterns": ["information_capacity", "mutual_information", "channel_coding"],
        "variables": {"state": "input_distribution", "channel": "p_y_given_x", "rate": "bits_per_use"},
        "conservation": ["information_inequality"], "structure": "channel_optimization",
    },
    "rate_distortion": {
        "id": "rate_distortion", "name": "Rate-Distortion Theory", "domain": "Information Theory",
        "equation": "R(D) = min_{p(x̂|x): E[d(x,x̂)] ≤ D} I(X; X̂)",
        "update_form": "lossy_compression_bound", "optimization": "tradeoff_rate_distortion",
        "fixed_points": "rate_distortion_function",
        "operators": ["constrain_distortion", "minimize_mi", "quantize"],
        "patterns": ["information_bottleneck", "compression_quality_tradeoff", "lagrangian"],
        "variables": {"state": "reconstruction", "rate": "R", "distortion": "D"},
        "conservation": ["data_processing_inequality"], "structure": "constrained_optimization",
    },
    "differential_entropy": {
        "id": "differential_entropy", "name": "Differential Entropy", "domain": "Information Theory",
        "equation": "h(X) = -∫ p(x) log p(x) dx",
        "update_form": "continuous_entropy", "optimization": "characterize_uncertainty",
        "fixed_points": "max_entropy_distribution",
        "operators": ["integrate", "log_density", "expectation"],
        "patterns": ["entropy", "continuous_information", "max_entropy"],
        "variables": {"state": "continuous_rv", "density": "p_x", "entropy": "h_x"},
        "conservation": ["differential_entropy_shift_invariance"], "structure": "continuous_information",
    },
    "minimum_description_length": {
        "id": "minimum_description_length", "name": "Minimum Description Length (MDL)", "domain": "Information Theory",
        "equation": "model* = argmin [L(data | model) + L(model)]",
        "update_form": "two_part_code", "optimization": "compression_based_modeling",
        "fixed_points": "optimal_model_complexity",
        "operators": ["compress_with_model", "encode_model", "sum_lengths"],
        "patterns": ["model_selection", "compression_inference", "occam_razor"],
        "variables": {"state": "model", "data_length": "L_data", "model_length": "L_model"},
        "conservation": ["total_code_length"], "structure": "two_part_mdl",
    },

    # ── Expand Cognitive Science (4 new) ──
    "global_workspace": {
        "id": "global_workspace", "name": "Global Workspace Theory (Baars)", "domain": "Cognitive Science",
        "equation": "consciousness ≈ broadcast from specialized modules to global workspace",
        "update_form": "competition_for_broadcast", "optimization": "integrate_information",
        "fixed_points": "consciously_attended_content",
        "operators": ["compete", "broadcast", "integrate"],
        "patterns": ["attention", "integration", "broadcast"],
        "variables": {"state": "workspace_content", "modules": "specialized_processors", "winner": "broadcast"},
        "conservation": ["attentional_capacity"], "structure": "competition_integration",
    },
    "dual_process_theory": {
        "id": "dual_process_theory", "name": "Dual Process Theory (System 1/2)", "domain": "Cognitive Science",
        "equation": "decision = system1_intuition + system2_deliberation",
        "update_form": "fast_slow_dual", "optimization": "balance_speed_accuracy",
        "fixed_points": "habitual_or_deliberate",
        "operators": ["intuit", "reason", "override"],
        "patterns": ["dual_process", "speed_accuracy_tradeoff", "metacognition"],
        "variables": {"state": "decision", "system1": "fast_intuition", "system2": "slow_reasoning"},
        "conservation": ["cognitive_resources"], "structure": "dual_system",
    },
    "memory_consolidation": {
        "id": "memory_consolidation", "name": "Memory Consolidation (Hippocampus-Neocortex)", "domain": "Cognitive Science",
        "equation": "memory transitions from hippocampal to neocortical over time",
        "update_form": "replay_based_transfer", "optimization": "stable_long_term_storage",
        "fixed_points": "consolidated_memory",
        "operators": ["replay", "transfer", "abstract"],
        "patterns": ["dual_storage", "replay_dynamics", "abstraction"],
        "variables": {"state": "memory_trace", "hippocampus": "episodic", "neocortex": "semantic"},
        "conservation": ["information_content"], "structure": "complementary_learning_systems",
    },
    "embodied_cognition": {
        "id": "embodied_cognition", "name": "Embodied Cognition", "domain": "Cognitive Science",
        "equation": "cognition = brain × body × environment",
        "update_form": "sensorimotor_coupling", "optimization": "action_perception_loop",
        "fixed_points": "skilled_action",
        "operators": ["sense", "act", "couple"],
        "patterns": ["sensorimotor_coupling", "action_perception", "situated_cognition"],
        "variables": {"state": "cognitive_state", "body": "morphology", "environment": "affordances"},
        "conservation": ["sensorimotor_contingencies"], "structure": "extended_cognition_loop",
    },

    # ── New: Pharmacology (4) ──
    "pk_pd_modeling": {
        "id": "pk_pd_modeling", "name": "PK-PD Modeling", "domain": "Pharmacology",
        "equation": "dC/dt = -k_e·C,  Effect = E_max·C/(EC50+C)",
        "update_form": "compartmental_kinetics", "optimization": "therapeutic_window",
        "fixed_points": "steady_state_concentration",
        "operators": ["absorb", "distribute", "metabolize", "excrete"],
        "patterns": ["compartmental_model", "saturation", "dose_response"],
        "variables": {"state": "concentration", "elimination": "k_e", "effect": "drug_response"},
        "conservation": ["drug_mass"], "structure": "ode_compartmental",
    },
    "receptor_binding": {
        "id": "receptor_binding", "name": "Receptor-Ligand Binding Kinetics", "domain": "Pharmacology",
        "equation": "B = B_max · [L] / (K_d + [L])",
        "update_form": "saturation_binding", "optimization": "characterize_affinity",
        "fixed_points": "equilibrium_binding",
        "operators": ["bind", "dissociate", "fit_hill"],
        "patterns": ["saturation", "equilibrium", "binding_kinetics"],
        "variables": {"state": "bound_fraction", "ligand": "concentration", "affinity": "K_d"},
        "conservation": ["receptor_total"], "structure": "binding_isotherm",
    },
    "dose_response": {
        "id": "dose_response", "name": "Hill Equation / Dose-Response", "domain": "Pharmacology",
        "equation": "E = E_max · [D]^n / (EC50^n + [D]^n)",
        "update_form": "cooperative_binding", "optimization": "potency_efficacy",
        "fixed_points": "max_effect",
        "operators": ["hill_function", "cooperativity", "saturate"],
        "patterns": ["sigmoidal_response", "cooperativity", "threshold_response"],
        "variables": {"state": "effect", "dose": "D", "potency": "EC50"},
        "conservation": ["max_effect_bound"], "structure": "sigmoid_curve",
    },
    "drug_synergy_combination": {
        "id": "drug_synergy_combination", "name": "Bliss/Loewe Drug Combination", "domain": "Pharmacology",
        "equation": "synergy = observed - expected_additive",
        "update_form": "combination_evaluation", "optimization": "maximize_synergy",
        "fixed_points": "synergistic_combination",
        "operators": ["combine", "compare_to_additive", "isobologram"],
        "patterns": ["combination_effect", "non_linearity", "interaction"],
        "variables": {"state": "combined_effect", "drug_a": "dose_a", "drug_b": "dose_b"},
        "conservation": ["additive_baseline"], "structure": "combination_index",
    },
}

# Load existing
theories_path = Path("client/src/data/theories.json")
with open(theories_path) as f:
    existing = json.load(f)

before = len(existing)
print(f"Before: {before} theories")
print(f"Adding: {len(NEW_THEORIES)} new theories")

# Check for duplicates
duplicates = set(NEW_THEORIES.keys()) & set(existing.keys())
if duplicates:
    print(f"WARNING: Duplicates skipped: {duplicates}")
    for d in duplicates:
        del NEW_THEORIES[d]

# Merge
existing.update(NEW_THEORIES)
after = len(existing)
print(f"After: {after} theories  (+{after - before})")

# Save
with open(theories_path, "w") as f:
    json.dump(existing, f, indent=2, ensure_ascii=False)

print(f"\nSaved to {theories_path}")

# Domain summary
from collections import Counter
domains = Counter(t.get("domain", "?") for t in existing.values())
print(f"\nDomain distribution:")
for d, c in sorted(domains.items(), key=lambda x: -x[1]):
    print(f"  {c:3d}  {d}")
